server {
  listen 80;
  server_name code.badcode.app;
  include /etc/nginx/custom_confs/proxy_common.conf;
  
  location / {
    proxy_pass http://172.31.255.255:7005;
    
    # uncomment after authentik setup
    include /etc/nginx/custom_confs/authentik_root.conf;
  }

  # uncomment after authentik setup
  include /etc/nginx/custom_confs/authentik.conf;
}
