server {
  listen 80;
  server_name guac.badcode.app;
  include /etc/nginx/custom_confs/proxy_common.conf;
  
  location / {
    return 301 https://guac.badcode.app/guacamole/;
  }

  location /guacamole/ {
    proxy_pass http://172.31.255.255:7000;
    include /etc/nginx/custom_confs/proxy_common.conf;
  }
}