server {
  listen 80;
  server_name www.badcode.app;
  include /etc/nginx/custom_confs/proxy_common.conf;
  
  location / {
    proxy_pass http://172.31.255.255:80;
    
    # uncomment after authentik setup
    #include /etc/nginx/custom_confs/authentik_root.conf;
  }

  # uncomment after authentik setup
  #include /etc/nginx/custom_confs/authentik.conf;
}

server {
  listen 80;
  server_name webtest.badcode.app;
  include /etc/nginx/custom_confs/proxy_common.conf;
  
  location / {
    proxy_pass http://172.31.255.255:81;
    
    # uncomment after authentik setup
    include /etc/nginx/custom_confs/authentik_root.conf;
  }

  # uncomment after authentik setup
  include /etc/nginx/custom_confs/authentik.conf;
}