voip:
  tftp:
    - model: "cmterm-78xx"
      version: "14-4-1-0101-153"
      files:
        - name: "kern2"
        - name: "kern78xx"
        - name: "rootfs2.78xx"
        - name: "sboot2.78xx"
        - name: "sboot78xx"
        - name: "sip78xx"
          ext: "loads"
    - model: "cmterm-88xx"
      version: "14-4-1-0101-153"
      files:
        - fixed: "boot1288xx.BE-01-007"
        - fixed: "fbi88xx.BE-01-012.sbn"
        - name: "kern88xx"
        - name: "kern288xx"
        - name: "kern388xx"
        - fixed: "m0patch288xx.BE-01-001.sbn"
        - fixed: "preloader88xx.BE-01-008.sbn"
        - name: "rootfs88xx"
        - name: "rootfs288xx"
        - name: "rootfs388xx"
        - fixed: "sb288xx.BE-01-028.sbn"
        - fixed: "sb2288xx.BE-01-015.sbn"
        - fixed: "sb2388xx.BE-01-032.sbn"
        - name: "sip88xx"
          ext: "loads"
        - fixed: "ssb288xx.BE-01-007.sbn"
        - name: "vc488xx"
  loads:
    - phones:
      - "7811"
      - "7821"
      - "7841"
      - "7861"
      loads_file: "sip78xx.14-4-1-0101-153.loads"
    - phones:
      - "8811"
      - "8841"
      - "8851"
      - "8851NR"
      - "8861"
      loads_file: "sip88xx.14-4-1-0101-153.loads"