#https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html

[ req ]
default_md = sha512
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no

[ req_distinguished_name ]
C   = US
O   = Foobar Infantry
CN  = TSS Root CA

[ req_ext ]
basicConstraints = critical, CA:TRUE, pathlen:0
  #pathlen: indicates the maximum number of CAs that can appear below in a chain
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
nsComment = "Happy to be here!"