[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no

# edit these
# define distinguished names as needed
[req_distinguished_name]
C   = US
O   = Foobar Infantry
CN  = macdads.net

[req_ext]
subjectAltName = @alt_names

# add SANs on "self-signed-cert-ext.conf"
# any below will be overridden
[alt_names]
DNS.1 = .