[ req ]
default_md = sha512
req_extensions = req_ext

[ req_ext ]
basicConstraints = CA:FALSE
authorityKeyIdentifier = keyid,issuer:always
subjectKeyIdentifier = hash
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
nsComment = "Happy to be here!"
  # add a comment if you're cool
subjectAltName = @alt_names

# edit these
# map to your domain and IPs
[alt_names]
DNS.1 = macdads.net
DNS.2 = *.macdads.net
IP.1 = 10.0.255.21
IP.2 = 10.0.255.22
IP.3 = 10.0.255.23