[req]
default_md = sha512
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no

[req_distinguished_name]
C   = US
O   = Foobar Infantry
CN  = macdads.net

[req_ext]
basicConstraints = CA:FALSE
#authorityKeyIdentifier = keyid,issuer:always
subjectKeyIdentifier = hash
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
nsComment = "Happy to be here!"
    # add a comment if you're cool
subjectAltName = @alt_names

# edit these
# this is your signing request
# you may still have to specify SANs in your request portal
[alt_names]
DNS.1 = tss.foobar.army.mil
DNS.2 = *.tss.foobar.army.mil
IP.1 = 10.0.20.33
IP.2 = 10.0.20.34
IP.3 = 10.0.20.35