[[inputs.exec]]
  commands = ["/usr/local/bin/poll_netconf.py"]
  timeout = "35s"
  interval = "60s"
  data_format = "json"
  name_override = "netconf_interfaces"
  tag_keys = ["interface", "admin_status", "oper_status"]

[[outputs.elasticsearch]]
  urls = ["http://127.0.0.1:9200"]
  username = "${ES_USER}"
  password = "${ES_PASSWORD}"

  # Target the data stream name
  index_name = "netconf-army-telegraf-%Y.%m.%d"
  # Disable legacy template pushing
  manage_template = false