---
services:
  www:
    command: [
      "--workers", "4",
      "--bind", "0.0.0.0:8080",
      "wsgi:app"
    ]
    environment:
      TZ: America/Denver
    build:
      target: www
      context: .
    ports:
      - 172.31.255.255:80:8080
    volumes:
      - ./app:/app
    restart: unless-stopped
  webtest:
    environment:
      TZ: America/Denver
    build:
      target: webtest
      context: .
    ports:
      - 172.31.255.255:81:5000
    volumes:
      - ./app:/app
    restart: unless-stopped