---
services:
  www:
    networks:
      - www
    environment:
      TZ: $TZ
      PYTHONPATH: /app/src
    build:
      context: ./app/nmas
    ports:
      - 172.31.255.255:80:8080
    volumes:
      - ./app/nmas:/app
      - ../golden_configs:/golden
    restart: unless-stopped
  webtest:
    networks:
      - www
    environment:
      TZ: $TZ
      PYTHONPATH: /app/src
    build:
      context: ./app/webtest
    ports:
      - 172.31.255.255:81:5000
    volumes:
      - ./app/nmas:/app
      - ../golden_configs:/golden
    restart: unless-stopped
networks:
  www:
    enable_ipv6: true