################
# Cisco Syslog #
################
# apply on your cisco devices for remote syslog
!
logging source-interface loopback0
service timestamps log datetime msec show-timezone year
ip ssh logging events
login on-failure log
login on-success log
!
archive
  log config
  hidekeys
  notify syslog
  logging enable
!
logging host 1.2.3.4 session-id hostname sequence-num-session