# for Kibana index for Cisco Syslog
# create scripted field "app.loglevel" from "app.severity"
# transform log severity to worded value in Kibana
# a nice to have feature
#
def n = doc['app.severity'].value;
if (n == 0) { emit("Emergency"); }
else if (n == 1) { emit("Alert"); }
else if (n == 2) { emit("Critical"); }
else if (n == 3) { emit("Error"); }
else if (n == 4) { emit("Warning"); }
else if (n == 5) { emit("Notice"); }
else if (n == 6) { emit("Informational"); }
else if (n == 7) { emit("Debug"); }
else { emit(""); }