[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

# Cisco
[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57000"

# Arista
[[inputs.gnmi]]
  addresses = [
    "[2600:bad:c0de::1]:6030",
    "[2600:bad:c0de::2]:6030",
    "[2600:bad:c0de::11]:6030",
    "[2600:bad:c0de::12]:6030",
    "[2600:bad:c0de::13]:6030",
    "[2600:bad:c0de::14]:6030"
  ]
  username = "cisco"
  password = "password"
  
  ## Explicitly disable TLS for plain-text gRPC
  tls_enable = false
  redial = "10s"

  [[inputs.gnmi.subscription]]
    name = "arista_interfaces"
    path = "/interfaces/interface/state"
    subscription_mode = "sample"
    sample_interval = "15s"

[[outputs.file]]
  files = ["stdout"]

[[outputs.elasticsearch]]
  urls = ["http://127.0.0.1:9200"]
  username = "${ES_USER}"
  password = "${ES_PASSWORD}"
  index_name = "network-telemetry-%Y.%m.%d"
  manage_template = false